### PR TITLE
introduce CMake

### PR DESCRIPTION
**Pull request by loriab**
Hi @ilyak,

1. This PR updates Intel `-openmp` to `-qopenmp`, which you should probably update in your repo, regardless of whether you consider this PR further.
2. A couple years ago, I mentioned that some Psi4 test cases were failing unless I dialed down optimization. I've isolated that further with Intel compilers:
  * PASS: `int.c` w/ `-O3` and w/o OpenMP
  * PASS: `int.c` w/ `-O1 -qopenmp`
  * FAIL (4/5 tests): `int.c` w/ `-O3 -qopenmp`
3. libefp has been building in Psi4 for a while now with (1) a copy of the libefp repo (at 1.2.1) and (2) under CMake, rather than Make. We're in the process of splitting out projects (to avoid code duplication and keep maintenance with the developers) while still keeping them tightly integrated in the build process. So this PR proposes contributing that cmake back to your upstream repo. The cmake won't interfere with your make build scheme, it just sits alongside. The cmake has all the following characteristics. The question for you is whether you want to introduce it into your code.
  * will build the efp library
    * as static or dynamic
    * w/ or w/o OMP
    * w/ gcc or icc
    * w/ certain degree of static system libraries
  * won't deal with `efpmd`. I could add this, but I'd have to add blas/lapack detection, with is rather voluminous
  * won't deal with testing with CTest
  * has an option to install fraglib files with `<name>_L` names like you do or turn them into `<name>` as Psi4 does, for compatibility with both
4. If you do want to pull in the CMake, the only remaining point to reconcile between your repo and what Psi4 uses is some extra library fragments. I've pulled in extra fragments from https://github.com/makefp/EFP_potentials/tree/master/gamess under longer names: https://github.com/psi4/psi4/tree/master/share/efpfrag . The former repo isn't active, so what do you think about pulling those frags into your libefp?
5. I'll also build a conda package for libefp. It'll look a lot like this one: https://anaconda.org/psi4/chemps2

This PR looks close to its final form, but I'm iterating through the Psi4 add-ons, so even if you like this PR unreservedly, don't merge it until it reaches final form. This is just to open the conversation. Let me know if you have any questions.

### CODE REVIEW

**Comment by ilyak** [comment]
Hi @loriab,
Does -fopenmp work with your icc version? I'd suggest -fopenmp instead of -qopenmp since the latter does not work with slightly older versions.

**Comment by loriab** [comment]
Yes, my `icc` and `icpc` (20`16.0.2`) list `-fopenmp` as an alternate option for `-qopenmp`. I don't actually use the config/intel* files, just noticed the deprecation warning during testing, so passed it along.

**Comment by ilyak** [comment]
Otherwise looks good. Let me know when it is ready to merge.

**Comment by loriab** [comment]
Great! I just switched the Intel flags to fopenmp.

I'd say this is ready to go except for a openmp linking error I noticed yesterday. I'd like to see if I can fix it w/o adding math detection to your repo.

Any thoughts on https://github.com/psi4/libefp/issues/1?

**Comment by loriab** [comment]
Thanks for the merge, @ilyak . There'll probably be a minor follow-up PR down the line to handle the openmp linking detail (It doesn't affect the building of libefp, only the linking of the consuming project) and the installation step of the fraglib/databases folder.

**Pull request merged**
