### PR TITLE
LAPACK detection and Psi4 updates

### PR DESCRIPTION
**Pull request by loriab**
Hi @ilyak, here's a few more changes; the last before the Psi4 1.1 release, I hope. In particular,

- [x] Remove that LAPACK_INTERJECT business that made assumptions about the static/dynamic-ness of the LAPACK libraries. Instead do a tiered scheme, where it looks for a CMake package file containing the BLAS/LAPACK libs. This is what is used when Psi4 builds libefp internally. The package file ensures that libefp is getting the same BLAS/LAPACK as Psi4 uses. This solves the problem where Psi4's fancy LAPACK detection could find ACML, static MKL, etc. but libefp's `find_package(LAPACK)` couldn't, so the Psi4 build would fail. That scheme isn't relevant to anyone building libefp on its own. For such persons, the search for the LAPACK package file will fail, and it'll default back to `find_package(LAPACK)`, just as it does currently. Anyone wanting to pass in specific libraries will use `-DLAPACK_LIBRARIES` now, rather than `-DLAPACK_INTERJECT`. This all sounds complicated, but for you it'll pretty much search for something obscure, not find it, and revert back to current behavior.
- [x] A few other updates of helper files that don't make much difference to libefp, but I try to keep them consistent with Psi4's versions.

FYI, libefp is no longer _required_ to build Psi4. We don't think less of it or anything, we're just minimizing required dependencies and setting all Add-Ons to off by default. libefp was an anomaly since it was integrated so early. The psi4 binary will still be distributed with libefp on. Building Psi4 _with_ libefp is just `cmake ... -DENABLE_libefp=ON ...`

I'm glad to answer any concerns. Then, please accept this upstream and mint a new tag, being sure to change [this](https://github.com/ilyak/libefp/blob/master/CMakeLists.txt#L3) accordingly. Thanks!

- [x] Ready to go

### CODE REVIEW

**Comment by loriab** [comment]
Thanks for the merge, @ilyak. Are a [line edit](https://github.com/ilyak/libefp/blob/master/CMakeLists.txt#L3) and tag coming?

**Comment by ilyak** [comment]
These are the only changes since the last release. I propose to wait and see if there will be more. Let me know closer to the psi4 release, I will tag then. There may be more changes before that.

**Comment by loriab** [comment]
Sure, I know it's vexing to increment version for just build fixes. It'll have to be at least a week before psi4 rc1, though, because there are things I can't finalize about packaging _before_ the tag. Thanks!

**Comment by loriab** [comment]
I notice there's been some additional code changes. What are the prospects for a tag, @ilyak?

**Comment by loriab** [comment]
Hi @ilyak, can I get a tag or a decline, please? Thanks.

**Comment by ilyak** [comment]
Next week. Ok?

**Comment by loriab** [comment]
Sure. We're going 1.1rc1 Wednesday, but then I'll be away for a couple weeks, so anytime then. Thanks!

**Comment by ilyak** [comment]
tagged 1.4.2

**Comment by loriab** [comment]
Thanks very much. Incorporated as of psi4/psi4#686.

**Pull request merged**
