### PR TITLE
odds & ends for py wrapping

### PR DESCRIPTION
**Pull request by loriab**
- [x] Add option to install extra headers, namespaced
- [x] Some LAPACK detection improvements
- [x] Add function to get the periodic box size

### CODE REVIEW

**Comment by loriab** [comment]
Consider, please, @ilyak, as I'd rather not build packages for non-upstream versions.

**Comment by loriab** [comment]
Also, you mentioned a bump to 1.5.0 but never made a tag?

Also, why remove [this](https://github.com/ilyak/libefp/commit/eed25b184b10c48f9dc15952d8e9a5b42adf1d54#diff-af3b638bc2a3e6c650974192a53c7291L55)? It dates back to https://github.com/ilyak/libefp/pull/1#issue-170807348 . Though Psi now just uses serial libefp to reduce headaches, that flag did fix a lot of problems.

**Comment by ilyak** [comment]
1.5.0 is a bump for the future release.

I thought that was a problem because of a broken compiler... Does the default opt level still causes problems?

**Comment by loriab** [comment]
Usually version bump is the last stage before release? Anyone pulling from head would think current version is 1.5.0. Btw, in future you may want to make an announcement/issue a week or so before releases to collect PRs. I know I tend to hoard changes until they've collected and proven themselves, and then I sometimes miss getting them into official releases.

My impression was that the `-O1` was a libefp+parallelism (possibly +compiler+psi4) bug. The compilers were 2016.0.2 and I know nothing ill of them. I'm not set up to redo all those variations, but if I get to that, I'll report it. Because psi4 switched to serial libefp (there were other, random problems with parallel libefp), I haven't been monitoring the issue as we've updated compilers. So, I've no proof that it's broken or fixed.

Thanks for the merge!

**Pull request merged**
